### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by KevinRichard-GM** [zarmstrong/-hlo-to-fvtt-pf2-public#13]
After importing a character from HLO with crafting, it appears none of the information comes over on the character sheet. If you close the character sheet and try to reopen it, nothing happens. This also happens if I manually try to import the character.

Looking at the web browser console log it shows the following error:

2foundry.js:319 
        
       TypeError: Cannot read properties of undefined (reading 'map')
[Detected 1 package: system:pf2e]
    at new exports.CraftingEntry (main.bundle.js:1:49251)
    at main.bundle.js:1:63981
    at Array.map (<anonymous>)
    at CharacterPF2e.getCraftingEntries (main.bundle.js:1:63969)
    at async CharacterSheetPF2e.prepareCraftingEntries (main.bundle.js:1:122410)
    at async CharacterSheetPF2e.getData (main.bundle.js:1:110953)
    at async CharacterSheetPF2e._render (foundry.js:3064:18)
    at async CharacterSheetPF2e._render (foundry.js:3766:5)

I captured the errors during the actual import process:

foundry.js:5122 
        
       game.data.version is deprecated since V9 in favor of game.version
get @ foundry.js:5122
importHLOCharacter @ hlo-importer.min.js:53
foundry.js:319 
        
       TypeError: Cannot read properties of undefined (reading 'map')
[Detected 1 package: system:pf2e]
    at new exports.CraftingEntry (main.bundle.js:1:49251)
    at main.bundle.js:1:63981
    at Array.map (<anonymous>)
    at CharacterPF2e.getCraftingEntries (main.bundle.js:1:63969)
    at async CharacterSheetPF2e.prepareCraftingEntries (main.bundle.js:1:122410)
    at async CharacterSheetPF2e.getData (main.bundle.js:1:110953)
    at async CharacterSheetPF2e._render (foundry.js:3064:18)
    at async CharacterSheetPF2e._render (foundry.js:3766:5)
onError @ foundry.js:319
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁Hooks.onError#lib-wrapper @ listeners.js:137
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
(anonymous) @ foundry.js:3025
Promise.catch (async)
render @ foundry.js:3023
render @ foundry.js:4261
render @ foundry.js:10808
_onUpdate @ foundry.js:10862
_onUpdate @ foundry.js:13748
_onUpdate @ main.bundle.js:1
_onUpdate @ main.bundle.js:1
callback @ foundry.js:10290
(anonymous) @ foundry.js:10241
_handleUpdateDocuments @ foundry.js:10241
_updateDocuments @ foundry.js:10121
await in _updateDocuments (async)
update @ backend.mjs:154
await in update (async)
updateDocuments @ document.mjs:373
update @ document.mjs:456
importFromJSON @ main.bundle.js:1
foundry.js:319 
        
       TypeError: Cannot read properties of undefined (reading 'map')
[Detected 1 package: system:pf2e]
    at new exports.CraftingEntry (main.bundle.js:1:49251)
    at main.bundle.js:1:63981
    at Array.map (<anonymous>)
    at CharacterPF2e.getCraftingEntries (main.bundle.js:1:63969)
    at async CharacterSheetPF2e.prepareCraftingEntries (main.bundle.js:1:122410)
    at async CharacterSheetPF2e.getData (main.bundle.js:1:110953)
    at async CharacterSheetPF2e._render (foundry.js:3064:18)
    at async CharacterSheetPF2e._render (foundry.js:3766:5)
onError @ foundry.js:319
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁Hooks.onError#lib-wrapper @ listeners.js:137
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
(anonymous) @ foundry.js:3025
Promise.catch (async)
render @ foundry.js:3023
render @ foundry.js:4261
render @ foundry.js:10808
_onCreateEmbeddedDocuments @ foundry.js:10909
_onCreateEmbeddedDocuments @ foundry.js:13777
_handleCreateEmbeddedDocuments @ foundry.js:10068
_createEmbeddedDocuments @ foundry.js:9957
await in _createEmbeddedDocuments (async)
create @ backend.mjs:95
await in create (async)
createDocuments @ document.mjs:338
createEmbeddedDocuments @ document.mjs:522
addEffect @ module.js:120
updateActor @ module.js:154
_call @ foundry.js:294
callAll @ foundry.js:253
callback @ foundry.js:10303
(anonymous) @ foundry.js:10241
_handleUpdateDocuments @ foundry.js:10241
_updateDocuments @ foundry.js:10121
await in _updateDocuments (async)
update @ backend.mjs:154
await in update (async)
updateDocuments @ document.mjs:373
update @ document.mjs:456
importFromJSON @ main.bundle.js:1
foundry.js:319 
        
       TypeError: Cannot read properties of undefined (reading 'map')
[Detected 1 package: system:pf2e]
    at new exports.CraftingEntry (main.bundle.js:1:49251)
    at main.bundle.js:1:63981
    at Array.map (<anonymous>)
    at CharacterPF2e.getCraftingEntries (main.bundle.js:1:63969)
    at async CharacterSheetPF2e.prepareCraftingEntries (main.bundle.js:1:122410)
    at async CharacterSheetPF2e.getData (main.bundle.js:1:110953)
    at async CharacterSheetPF2e._render (foundry.js:3064:18)
    at async CharacterSheetPF2e._render (foundry.js:3766:5)
onError @ foundry.js:319
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁Hooks.onError#lib-wrapper @ listeners.js:137
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
(anonymous) @ foundry.js:3025
Promise.catch (async)
render @ foundry.js:3023
render @ foundry.js:4261
render @ foundry.js:10808
_onUpdate @ foundry.js:10862
_onUpdate @ foundry.js:13748
_onUpdate @ main.bundle.js:1
_onUpdate @ main.bundle.js:1
callback @ foundry.js:10290
(anonymous) @ foundry.js:10241
_handleUpdateDocuments @ foundry.js:10241
_updateDocuments @ foundry.js:10121
await in _updateDocuments (async)
update @ backend.mjs:154
await in update (async)
updateDocuments @ document.mjs:373
update @ document.mjs:456
importHLOCharacter @ hlo-importer.min.js:53
[Violation] Forced reflow while executing JavaScript took 52ms

1. Create new PC 
2. Click on import from HLO
3. Close the character sheet once import is finished
4. Try to reopen character, nothing happens.

**File ID this error occurred with**
y6N4zWuXipf3PAtI

**Comment by KevinRichard-GM** [comment]
Appears the latest PF2 ruleset update for FoundryVTT fixed the issue.

**Comment by zarmstrong** [comment]
Thanks for the update @KevinRichard-GM . Glad that resolved it for you!
